# **Numpy : 숫자와 관련한 파이썬 도구**

- numpy array - 배열 (행렬) 다룰 때 주로 씀

In [1]:
import numpy

In [3]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [4]:
array11

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

## .shape : 행렬의 차원

In [6]:
array1.shape

(11,)

## type( ): 자료형

In [5]:
type(array1)

numpy.ndarray

- ndarray : n차원 배열

In [7]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
type(array2)

numpy.ndarray

In [9]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array2.shape 

(3, 4)

- (3,4) : 행 3, 열 4 (2차원)

## size : 전체 배열 크기

In [11]:
array1.size

11

In [12]:
array2.size

12

# numpy.full() : 균일한 값으로 생성

In [13]:
array3 = numpy.full(6,7)
array3

array([7, 7, 7, 7, 7, 7])

# 모든 값이 0인 numpy array 생성

In [14]:
x = numpy.full(6, 0)
y = numpy.zeros(6, dtype=int)

print(x)
print()
print(y)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


- numpy.zeros(6, dtype=int)

# 모든 값이 1인 numpy array 생성

In [15]:
x = numpy.full(6,1)
y = numpy.ones(6, dtype=int)

print(x)
print()
print(y)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


# 랜덤 값 생성

- `numpy` 모듈 안에 `random` 모듈 안에 `random` 함수

In [16]:
x = numpy.random.random(6)
y = numpy.random.random(6)

print(x)
print()
print(y)

[0.11053341 0.34554558 0.02474761 0.72489176 0.63726219 0.70284287]

[0.0204463  0.55884753 0.90544779 0.26879676 0.89377014 0.57802674]


# 연속 배열 numpy array 생성

- `arange(n)` : `0`부터 `n-1`까지

In [18]:
x = numpy.arange(6)
print(x)

[0 1 2 3 4 5]


- `arange(n, m)` : `n`부터 `m-1`까지

In [19]:
y = numpy.arange(2,7)
print(y)

[2 3 4 5 6]


- `arange(n, m, s)` : `n`부터 `m-1`까지 `s` 간격으로

In [20]:
z = numpy.arange(3, 17, 3)
print(z)

[ 3  6  9 12 15]
